### ISSUE TITLE
Links to binaries are broken

### ISSUE THREAD

**Issue by jgarciamesa** [benb/MetAl#1]
I was wondering if the links to the binaries could be updated.
I tried building MetAl from source but I am having issues with a deprecated dependency of phytree.
Thank you!

**Comment by AAdamCCox** [comment]
Hi @jgarciamesa I was able to get a copy of the Linux binary from a colleague who's used it previously, hope this helps!
[metal-linux64-1.1.zip](https://github.com/benb/MetAl/files/7277021/metal-linux64-1.1.zip)

**Comment by jgarciamesa** [comment]
This is great, thank you so much!
